apiVersion: v1
kind: Service
metadata:
  name: user-review-service
spec:
  selector: 
    app: user-review-service
  ports:
    - protocol: 'TCP'
      port: 3003
      targetPort: 3003
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer