apiVersion: v1
kind: Service
metadata:
  name: bookbox-ui
spec:
  selector:
    app: bookbox-ui
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 80
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer
